### ISSUE TITLE
Is it possible to assign values to report variables from code?

### ISSUE THREAD

**Issue by teilin** [stimulsoft/Samples-NET.Core-CSharp#1]
Hi,

I have been looking into Stimulsoft NetCore package and have not been able to figure out how I can set report variables and send it to the report viewer.

In the report I have defined two variables that I am using in the report definition, but what I want is to be able to pass values from code.

Is there any documentation somewhere as well?

**Comment by LeshikSat** [comment]
Hello,

At the current moment, variables are not fully implemented. We will try to add improvements and update samples on this week.

**Comment by teilin** [comment]
Okey, that explains quite a bit. I will keep watching this repo for updates.

**Comment by teilin** [comment]
Hi, how are you doing on this? Do you have any schedule about the report variables and the sample you mentioned?

**Comment by AntonLozovskiy** [comment]
Hell,

This will be available during 1 week.

Thank you.

**Comment by VladimirBLR** [comment]
Hello,

Please see the "Show-Report-with-Parameters" sample for new version 2017.1.0.4
https://github.com/stimulsoft/Samples-NET.Core-CSharp/tree/master/Show-Report-with-Parameters

Thank you.

**Comment by teilin** [comment]
Thanks, that looks great. I will test this out a bit later today. But after just been looking at your implementation, it looks pretty clean and easy.

**Comment by teilin** [comment]
Okey, this works great so thank you. I close this one now.
