### ISSUE TITLE
Activate licence for Stimulsoft 2017.1

### ISSUE THREAD

**Issue by teilin** [stimulsoft/Samples-NET.Core-CSharp#3]
Hi,

I am using [Stimulsoft Reports.Web for .NET Core 2017.1.0-rc6](https://www.nuget.org/packages/Stimulsoft.Reports.NetCore/2017.1.0-rc6) and I need activate it so I do not get the TRIAL watermark in the report.

I have tried with the licence I have (did not really think that would work since that was 2015.3), but at your website you mention 2016.1, but can not find anything about 2017.1.

Where do I get the correct licence to use with this pavkage?

**Comment by VladimirBLR** [comment]
Hello,

Starting from the release 2017.1, you will need to use an activation code or license key to activate Stimulsoft products. From your personal account you should click the How to Activate button, copy the activation code or download the license key (license.key) and apply them following the elaborate instructions given right under the activation option. You need to run this code one time when you start your application or service. Find more detailed information on product activation from your account.

**Comment by teilin** [comment]
Thanks for your quick reply. I will take a look at that.

**Comment by kubekin2** [comment]
Thanks for your question.
