### ISSUE TITLE
StiReport Option is not available to create report from code behind

### ISSUE THREAD

**Issue by saliniashok** [stimulsoft/Samples-NET.Core-CSharp#4]
In the older version, it was possible to create report dynamically using C# code. It was done by using StiReport, StiTable etc classes available with Stimulsoft. But it seems like these options are not available with .Net core. My requirement is to generate report dynamically from the code.  We may need to create dynamic table with dynamic columns or need to create chart dynamically based on some configuration.
Is there any option to create a report using Stimulsoft.Report.NetCore

**Comment by VladimirBLR** [comment]
Hello,

Due to the engine based on JS code, the server side only serves to manage reports and data.
Unfortunately, at the current moment, it is not possible in the NET Core.

Alternatively, you can use the JS library and Node.js on the server side to programmatically create, generate, and export the report. Please see the following samples:
https://github.com/stimulsoft/Samples-NET.Core-CSharp/tree/master/Render-Report-from-Code
https://github.com/stimulsoft/Samples-NET.Core-CSharp/tree/master/Export-Report-from-Code

Thank you.

**Comment by saliniashok** [comment]
Hi,
Thanks for the response.

I have gone through the the sample Render-Report-from-Code and created mdc file using node service and able to load the same in to the report viewer.

Could you please provide more details or links on how to dynamically create the report using node js.

Thanks,
Salini

**Comment by AlexKulikow** [comment]
Hello,

Please check the following sample:
https://www.stimulsoft.com/en/samples/js/print-table-from-code

**Comment by saliniashok** [comment]
Hi,

Using the sample that you have given above, I have created a report to just add a footer text into an existing report by using the code below in the renderReport.js file in the Render-Report-from-Code sample. But its seems not working. Is there any issue with my code below. 
Please note that I am modifying the Render-Report-from-Code sample available in github and trying to do add a custom control ( a Text Control or Table Control) into report file and needs to render the same into .net core report viewer

odule.exports = function (callback, reportPath) {
    // Prepare engine module
    var Stimulsoft = require('stimulsoft-reports-js');
    Stimulsoft.Base.StiFontCollection.addOpentypeFontFile("node/Roboto-Black.ttf");

    // Load and render the report template
    var report = new Stimulsoft.Report.StiReport();
    report.loadFile(reportPath);

    console.log('Report loaded successfully ');

    var page = report.pages.getByIndex(0);

    console.log('Got page');
    //console.log(page);

    //Create FooterBand
    var footerBand = new Stimulsoft.Report.Components.StiFooterBand();
    footerBand.height = 0.5;
    footerBand.name = "FooterBand";
    page.components.add(footerBand);
    console.log('Got page components');
    //console.log(page.components);

    //Create text on footer
    var footerText = new Stimulsoft.Report.Components.StiText();
    footerText.clientRectangle = new Stimulsoft.Base.Drawing.RectangleD(0, 0, page.width, 0.5);
    footerText.text = "Footer";
    footerText.horAlignment = Stimulsoft.Base.Drawing.StiTextHorAlignment.Right;
    footerText.name = "FooterText";
    footerText.brush = new Stimulsoft.Base.Drawing.StiSolidBrush(Stimulsoft.System.Drawing.Color.lightGreen);
    footerBand.components.add(footerText);
    console.log('Got footer components');
    //console.log(footerBand.components);

    report.render();

    report.renderAsync(function () {
        // Return JSON report document
        var jsonDocument = report.saveDocumentToJsonString();
        console.log("Report JSON");
        console.log(jsonDocument);
        console.log("Report JSON End");
        callback(/* error */null, jsonDocument);
    });
};

Thanks,
Salini

**Comment by VladimirBLR** [comment]
Hello,

You can use NodeServices in the GetReport viewer action, for example:

`public async Task<IActionResult> GetReport([FromServices] INodeServices nodeServices)
{
    string fileName = "SimpleList";
    string reportPath = "./Reports/" + fileName + ".mrt";
    string result = await nodeServices.InvokeAsync<string>("./node/renderReport", reportPath);

    return StiNetCoreViewer.GetReportResult(this, result);
}`

Thank you.

**Comment by saliniashok** [comment]
Hi,
Thank you again for your guidance.

The above code is working fine for me.

But i tried to modify the renderReport.js file in such a way that i can add a footer text to the existing report.
But it seems not working

My code is attaching below, the same i have given before

`module.exports = function (callback, reportPath) {
    // Prepare engine module
    var Stimulsoft = require('stimulsoft-reports-js');
    Stimulsoft.Base.StiFontCollection.addOpentypeFontFile("node/Roboto-Black.ttf");

    // Load and render the report template
    var report = new Stimulsoft.Report.StiReport();
    report.loadFile(reportPath);

    console.log('Report loaded successfully ');

    var page = report.pages.getByIndex(0);

    console.log('Got page');
    //console.log(page);

    //Create FooterBand
    var footerBand = new Stimulsoft.Report.Components.StiFooterBand();
    footerBand.height = 0.5;
    footerBand.name = "FooterBand";
    page.components.add(footerBand);
    console.log('Got page components');
    //console.log(page.components);

    //Create text on footer
    var footerText = new Stimulsoft.Report.Components.StiText();
    footerText.clientRectangle = new Stimulsoft.Base.Drawing.RectangleD(0, 0, page.width, 0.5);
    footerText.text = "Footer";
    footerText.horAlignment = Stimulsoft.Base.Drawing.StiTextHorAlignment.Right;
    footerText.name = "FooterText";
    footerText.brush = new Stimulsoft.Base.Drawing.StiSolidBrush(Stimulsoft.System.Drawing.Color.lightGreen);
    footerBand.components.add(footerText);
    console.log('Got footer components');
    //console.log(footerBand.components);

    report.render();

    report.renderAsync(function () {
        // Return JSON report document
        var jsonDocument = report.saveDocumentToJsonString();
        console.log("Report JSON");
        console.log(jsonDocument);
        console.log("Report JSON End");
        callback(/* error */null, jsonDocument);
    });
};`

**Comment by VladimirBLR** [comment]
I close the issue, because for you it's solved.
If you have any questions please create a new topic.

Thank you.
